// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int randoms = Integer.parseInt( args[0]);
		double random;
		double graterThenHalf=0;
		double lessOrEqualThenHalf=0;
		while(randoms!=0){
			random=Math.random();
			if (random>0.5){
				graterThenHalf++;
			}
			else{
				lessOrEqualThenHalf++;
			}
			randoms--;
		}
		if (graterThenHalf<lessOrEqualThenHalf){
			System.out.println(graterThenHalf/lessOrEqualThenHalf);;
		}
		else{
			System.out.println(lessOrEqualThenHalf/graterThenHalf);;
		}
		
	}
}
